name: addresses_converter
description: Скрипт исправления задач и пользователей в части списка населенных пунктов и адресов
version: 0.0.1
author: Sergey.Kablov <skablov@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  rethinkdb_driver2: "^2.3.1"
  http_client: "^0.3.0"
  queries: "^0.0.15"
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
