name: addresses_converter
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: Серега <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  rethinkdb_driver2: "^2.3.1"
  http_client: "^0.3.0"
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
